# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a5db41d382c342ac8bac5fb4aca876b993b1a5312b9dcd83304f318fecf52b1b23f1e2f59e603621a385357d706ff7675c3cf4752480b7d496428472c5162e2

test:
  secret_key_base: 20e09c19bfe7fba90ddfd641471f584109d2f0cc65bebb8c83ea3e61a4488700c33c22cfba51fadd5f3a7ecb14ca2ccec12c1fc04436b6e4f86fa693f07a5371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
